---
# Source: community-operator/templates/operator_roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-operator
  namespace: default
---
# Source: community-operator/templates/operator_roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole 
metadata:
  name: mongodb-kubernetes-operator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodbcommunity.mongodb.com
  resources:
  - mongodbcommunity
  - mongodbcommunity/status
  - mongodbcommunity/spec
  - mongodbcommunity/finalizers
  verbs:
  - get
  - patch
  - list
  - update
  - watch
---
# Source: community-operator/templates/operator_roles.yaml
kind:  ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
  namespace: default
roleRef:
  kind:  ClusterRole 
  name: mongodb-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
