---
# Source: eck-operator/templates/role-bindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding 
metadata:
  name: elastic-operator
  labels:
    
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/instance: eck-operator
    app.kubernetes.io/version: "2.12.1"
    helm.sh/chart: eck-operator-2.12.1
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-operator
subjects:
- kind: ServiceAccount
  name: elastic-operator
  namespace: default
