---
# Source: eck-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-operator
  namespace: default
  labels:
    
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/instance: eck-operator
    app.kubernetes.io/version: "2.12.1"
    helm.sh/chart: eck-operator-2.12.1
    app.kubernetes.io/managed-by: Helm
